# Generated by Django 4.0.4 on 2022-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('stok', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
